# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7488f225842b6d7d03a24948844d1aaffdaf233e4238a105511b9d3042f22f4174e48c6a8dfb718e76279ab8515614dd350062f495bb160b0bd57426e98ab7c

test:
  secret_key_base: c833e519e1558d525d8c683b331f8568f94f86fd0224f1d4d1578089f02c70538c6209d1450df413a45b830e7f7ae9a9bd35ae80027386d25f2febc65d7bd949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
